const yoga={
  
pose1:{
   pose:"Lord of the Dance or Natarajasana:",
   poseSteps:"Press down through your big toe mounds and lift your inner arches. Rotate your inner thighs toward the wall behind and release your tailbone down.                                                           Bring your right knee alongside your left knee. Pause and observe which of the elements from Tadasana have been lost. To bring your body back into symmetry, press down with your left big toe mound, draw your left outer hip into the midline, and bring the right side of your pelvis and chest forward in line with your left.                                            Maintain the symmetry in your body as you start to press your right thigh back and up. Lead with your inner thigh and press your right big toe mound away from you. Simultaneously reach your left arm forward and up, leading with your inner upper arm.                                                                     Reach your sternum away from your navel to maintain the lift of your chest while you extend back and up with your right thigh. Keep your right knee in toward the midline rather than splay it out to the side.                                                   Hold for 5-10 breaths, then release back to Tadasana.                                                       Repeat on the other side."
  },
pose2:{
   pose:"Virabhadrasana-2:",
   poseSteps:"Face the long side of your mat, arms stretched out to the sides with your feet parallel to each other in a wide stance so your feet are approximately beneath your hands.                                               Turn your right foot and knee to face the front of the mat.                                                Turn your left toes slightly toward your right foot. Line up your right heel with your left inner arch.                                                    Bend your right knee and stack it over your right ankle.                                                Press your left thigh bone back while releasing your tailbone down.                                                   Keep the crown of your head stacked over your pelvis and your shoulders over your hips.                                                     Reach strongly through both arms toward the front and back of the mat and turn and look past your right fingertips.                                           Hold for 5–10 breaths.                           To exit, press down through your feet on an exhalation, then use an inhalation to straight your legs and return your feet to parallel facing the left long side of the mat.                                       Repeat on the other side.     "
  },  
pose3:{
  pose:"Urdhva Mukha Shvanasana or Upward Facing Dog:",
  poseSteps:"Begin on your belly with your feet hip-distance apart and your hands placed beside your lower ribs.                                                                  Extend your legs and press down with all ten toenails to activate your quadriceps.                                                                 Rotate your inner thighs to the ceiling while firming your outer ankles into your midline.                                                                    Press down with your hands and feet.                                                               On an inhalation, straighten your arms and lift your legs.                                                         With your arms perpendicular to the floor, your feet anchored, and your legs active, draw your chest forward and up.                                                                        Draw your shoulders back while rooting down with your hands.                                                      Make sure that the curve of your neck is a continuation of the curve of your mid and upper back.                                              Hold for 5 breaths, then release."
},  
pose4:{
  pose:"Adho Mukha Svanasana or Downward Facing Dog",
  poseSteps:"Come onto your hands and knees, with your hands a tiny bit in front of your shoulders and your knees directly below your hips. Spread your palms, rooting down through all four corners of your hands, and turn your toes under.                                                             Exhale and lift your knees from the floor, at first keeping your knees slightly bent and your heels lifted off the floor. Lengthen your tailbone away from the back of your pelvis, lift the sitting bones toward the ceiling, and draw your inner legs from your inner ankles up through your groins.                                                                              On an exhalation, push your top thighs back and stretch your heels toward the floor. Straighten your knees without locking them.                                                                          Firm your outer arms and press the bases of your index fingers actively into the floor. Lift along your inner arms from the wrists to the tops of the shoulders. Firm your shoulder blades against your back, then widen them and draw them toward your tailbone. Keep your head between your upper arms.                                                                         Stay in the pose for 10 or more breaths, then bend your knees on an exhalation and lower yourself into Child’s Pose"
},
pose5:{
  pose:"Reverse Warrior or Viparita Virabhadrasana",
  poseSteps:"Starting in Warrior 2 with the right knee bent, turn the palm of your right hand to face the ceiling.                                                                                     As you inhale, lift your right arm up to the ceiling. At the same time lower your left hand and slide it down your left leg. Think about keep length in both your side waists as you do so.                                                                             Firm your shoulder blades on the back and knit your lower ribs in, slightly engaging your core muscles.                                                                  Lift your chest as you come into a gentle backbend.                                                                        Look to your raised hand or gaze to your back foot if you have neck or balance issues.                                                                                Stay in the pose for up to 5 breaths.                                               Come back to Warrior 2 as you exhale.                                Repeat on the other side."
},
pose6:{
  pose:"Half Moon Pose or Ardha Chandrasana",
  poseSteps:"Begin in Triangle Pose (trikonasana) with the right leg forward. Bend your right knee softly and bring your left hand to your hip.                                               Bring your right hand to the floor in front of your right foot. Your hand should be under your shoulder when you are in the full pose, so in order to set it up in the correct position, place it about a foot in front of and 5 or 6 inches to the right of your right foot. Tent your hand so that just your fingertips on the floor.                                                                                             Begin to straighten your right leg while simultaneously lifting your left foot off the floor. Keep your left leg as straight as possible.                                                              Open your hips, stacking the left hip point on top of the right hip point.                                                                                   Bring your left leg straight and parallel to the floor. Flex your left foot strongly with the toes pointing toward the left side of the room.                                                                       When you feel balanced on the right leg, reach the left arm up toward the ceiling, opening the chest and making a straight line with the right and left arms perpendicular to the floor.                                                     Finally, turn your head so that your gaze is lifted toward your upraised left fingertips.                                                            The balance here for around five breaths before releasing the left leg to the floor and repeating the pose on the other side."
},
pose7:{
  pose:"Extended Side Angle Pose",
  poseSteps:"Start in Tadasana (Mountain Pose). Jump your legs about 4 feet apart. Extend your arms into a T position, with your palms facing down; reach out through the fingertips as if your arms were being pulled in opposite directions.                                                       Turn your left foot out to 90 degrees, and turn your right foot slightly inward. Lift through your spine, keeping the sides of your torso equally long.                                              Press your right outer foot and heel to the floor as you bend your left knee toward a 90-degree angle with your left thigh parallel to the floor. Adjust your stance to establish a strong foundation.                                                                         Lean toward your left knee, hinging at the hips to bring your left arm own toward the floor. You may place your left fingertips to the ground or on a block. Move your left armpit close to the outer left knee so your arm and shin are parallel.                                                             Reach your right arm up over your right ear, palm facing the floor. Turn your chest toward your raised arm and press the right hip toward the floor to create a straight line from your right ankle to you.                                                                      Turn your head to look past your right thumb. Breathe freely in the pose. Stay for 30 to 60 seconds.                                                  Inhale reach up then bring your torso up and straighten the left leg. Switch sides"
},
pose8:{
   pose:"Tree Pose",
   poseSteps:" Tree pose often starts from mountain pose (or Tadasana), with both feet planted firmly on the ground and your weight adequately distributed so that you are balanced.                                                               Bend one leg at the knee. Choose the leg you are going to fold in first. If your left leg is your standing leg, keep your left foot planted on the ground, and slowly bend in your right leg at the right knee so that the sole of your right foot rests against your left inner thigh (known as the half-lotus position in Bikram yoga).                                                                                    Point the knee of your bent leg outward, away from your body.                                                                   Lengthen your body. Clasp your hands together in the prayer position and raise your arms above your head.                                                         In this form, your head, shoulders, pelvis, and left foot should align vertically. The top of your torso should lift slightly, with your tailbone extending towards the ground.                                                                Hold and repeat. Hold the pose for as long as necessary, making sure to breathe properly. When you’re ready to switch legs, exhale, and return to mountain pose to start again."
},
pose9:{
  pose:"Side Plank or Vasisthasana:",
  poseSteps:"Begin in Downward-Facing Dog Pose.                                           Shift forward into Plank Pose.                                                      Roll onto the outside edge of your right foot, and stack your left foot on top of your right.                                                               Swing your left hand onto your left hip, turning your torso to the left as you do.                                                             Support the weight of your body on the outer right foot and right hand.                                                          Align your body into one long diagonal line from your heels to the crown of your head.                                                             Stretch your left arm toward the ceiling, so it is in line with your shoulders.                                                 Keep your head neutral, or gaze up at the left hand.                                                                        Stay in the position for several breaths, then return to Plank and repeat on the other side."
},
    }
export default yoga;